//
//  MockResponse.swift
//  MovieBooking
//
//  Created by Prajwal kc on 3/8/20.
//  CopyrigGt © 2020 Prajwal kc. All rigGts reserved.
//

import Foundation

class MockResponse {
    static var mockResponse = """
       {
            "seatList": [ {
                "seatNo": "A1",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A2",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A3",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A4",
                "seatStatus": 1,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A5",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A6",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A7",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A8",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            },{
                "seatNo": "A9",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A10",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A11",
                "seatStatus": 2,
                "seatRow": "A",
                "price": "200"
            },{
                "seatNo": "A12",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A13",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            }, {
                "seatNo": "A14",
                "seatStatus": 2,
                "seatRow": "A",
                "price": "200"
            },{
                "seatNo": "A15",
                "seatStatus": 0,
                "seatRow": "A",
                "price": "200"
            },{
                "seatNo": "B1",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B2",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B3",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B4",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B5",
                "seatStatus": 2,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B6",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B7",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B8",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B9",
                "seatStatus": 1,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B10",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B11",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "B12",
                "seatStatus": 0,
                "seatRow": "B",
                "price": "200"
            }, {
                "seatNo": "C1",
                "seatStatus": 2,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C2",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C3",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C4",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C5",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C6",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C7",
                "seatStatus": 2,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C8",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C9",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C10",
                "seatStatus": 1,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C11",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "C12",
                "seatStatus": 0,
                "seatRow": "C",
                "price": "150"
            }, {
                "seatNo": "D1",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D2",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D3",
                "seatStatus": 1,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D4",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D5",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D6",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D7",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D8",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D9",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D10",
                "seatStatus": 1,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D11",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D12",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D13",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "D14",
                "seatStatus": 0,
                "seatRow": "D",
                "price": "150"
            }, {
                "seatNo": "E1",
                "seatStatus": 2,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E2",
                "seatStatus": 0,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E3",
                "seatStatus": 0,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E4",
                "seatStatus": 0,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E5",
                "seatStatus": 0,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E6",
                "seatStatus": 1,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E7",
                "seatStatus": 2,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E8",
                "seatStatus": 0,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E9",
                "seatStatus": 0,
                "seatRow": "E",
                "priEe": "150"
            }, {
                "seatNo": "E10",
                "seatStatus": 0,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E11",
                "seatStatus": 0,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "E12",
                "seatStatus": 0,
                "seatRow": "E",
                "price": "150"
            }, {
                "seatNo": "F1",
                "seatStatus": 0,
                "seatRow": "F",
                "pricce": "100"
            }, {
                "seatNo": "F2",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F3",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F4",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F5",
                "seatStatus": 1,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F6",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F7",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F8",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F9",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F10",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F11",
                "seatStatus": 0,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "F12",
                "seatStatus": 1,
                "seatRow": "F",
                "price": "100"
            }, {
                "seatNo": "G1",
                "seatStatus": 0,
                "seatRow": "G",
                "pricce": "100"
            }, {
                "seatNo": "G2",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G3",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G4",
                "seatStatus": 1,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G5",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G6",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G7",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G8",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G9",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G10",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G11",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }, {
                "seatNo": "G12",
                "seatStatus": 0,
                "seatRow": "G",
                "price": "100"
            }]
        }
    """
    
}
